# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_ARCH_MXC) += imx8mp-astrial.dtb
dtb-$(CONFIG_ARCH_MXC) += imx8mp-astrial-disable-all.dtb
dtb-$(CONFIG_ARCH_MXC) += imx8mp-astrial-enable-all.dtb
dtb-$(CONFIG_ARCH_MXC) += imx8mp-astrial-flexcan2.dtb
dtb-$(CONFIG_ARCH_MXC) += imx8mp-astrial-sdhc1.dtb
dtb-$(CONFIG_ARCH_MXC) += imx8mp-astrial-spi2.dtb
dtb-$(CONFIG_ARCH_MXC) += imx8mp-astrial-uart3.dtb
dtb-$(CONFIG_ARCH_MXC) += imx8mp-astrial-dsi-rpi.dtb
dtb-$(CONFIG_ARCH_MXC) += imx8mp-astrial-dsi-waveshare.dtb
